version: '2'
services:
    nginx:
        build: .
        container_name: nginx-php7
        ports:
            - "8081:80"
        volumes:
            - ./public:/data/www/public
        working_dir: /data/www/public
        links:
            - mysql
        environment:
           - MYSQL_DATABASE=user_service
           - MYSQL_USER=user_mysql
           - MYSQL_PASSWORD=user_@123mysql
    mysql:
        image: mysql:5.6.26
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=user_service
          - MYSQL_USER=user_mysql
          - MYSQL_PASSWORD=user_@123mysql
        expose:
          - "3306"